package com.example.translationapp

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.DropdownMenu
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            // Use the default MaterialTheme generated by the template
            MaterialTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    ConversationScreen()
                }
            }
        }
    }
}

@Composable
fun ConversationScreen() {
    var inputLanguage by remember { mutableStateOf("English") }
    var outputLanguage by remember { mutableStateOf("Chinese") }

    var userMessage by remember { mutableStateOf("Tap the mic and speak…") }
    var translatedMessage by remember { mutableStateOf("Translation will appear here…") }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp)
    ) {

        // ---------- TOP PANEL (Translated output) ----------
        ConversationPanel(
            title = outputLanguage,
            text = translatedMessage,
            micLabel = "🎤",
            onMicClick = {
                // For now just simulate speaking in the target language
                translatedMessage = "你好，这是一个示例翻译。"
            }
        )

        Spacer(modifier = Modifier.height(12.dp))

        // ---------- LANGUAGE + SWAP BAR ----------
        Row(
            modifier = Modifier.fillMaxWidth(),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.SpaceBetween
        ) {
            LanguageDropdown(
                current = inputLanguage,
                onSelect = { inputLanguage = it }
            )

            Button(
                onClick = {
                    val tmp = inputLanguage
                    inputLanguage = outputLanguage
                    outputLanguage = tmp

                    // Optional: also swap text placeholders
                    val t = userMessage
                    userMessage = translatedMessage
                    translatedMessage = t
                },
                contentPadding = PaddingValues(horizontal = 12.dp, vertical = 4.dp)
            ) {
                Text("⇅ Swap")
            }
        }

        Spacer(modifier = Modifier.height(12.dp))

        // ---------- BOTTOM PANEL (User speech input) ----------
        ConversationPanel(
            title = inputLanguage,
            text = userMessage,
            micLabel = "🎙",
            onMicClick = {
                // Fake recording result for now
                userMessage = "This is a sample spoken sentence."
                translatedMessage = "这是一个示例句子的翻译。"
            }
        )
    }
}

@Composable
fun ConversationPanel(
    title: String,
    text: String,
    micLabel: String,
    onMicClick: () -> Unit
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .height(230.dp)
            .border(1.dp, Color.Gray, RoundedCornerShape(12.dp))
            .padding(10.dp)
    ) {
        Text(
            text = title,
            style = MaterialTheme.typography.labelLarge,
            fontWeight = FontWeight.Bold,
            color = Color.DarkGray
        )

        Spacer(modifier = Modifier.height(6.dp))

        Box(
            modifier = Modifier
                .weight(1f)
                .fillMaxWidth()
                .background(Color(0xFFF5F5F5), RoundedCornerShape(10.dp))
                .padding(10.dp)
                .verticalScroll(rememberScrollState())
        ) {
            Text(
                text = text,
                style = MaterialTheme.typography.bodyMedium,
                color = Color.Black.copy(alpha = 0.9f)
            )
        }

        Spacer(modifier = Modifier.height(8.dp))

        Button(
            modifier = Modifier.align(Alignment.CenterHorizontally),
            onClick = onMicClick,
            colors = ButtonDefaults.buttonColors(
                containerColor = MaterialTheme.colorScheme.primary
            ),
            contentPadding = PaddingValues(horizontal = 16.dp, vertical = 6.dp)
        ) {
            Text(micLabel)
            Spacer(modifier = Modifier.width(6.dp))
            Text("Speak")
        }
    }
}

@Composable
fun LanguageDropdown(current: String, onSelect: (String) -> Unit) {
    var expanded by remember { mutableStateOf(false) }

    Box {
        OutlinedButton(onClick = { expanded = true }) {
            Text(current)
        }

        DropdownMenu(
            expanded = expanded,
            onDismissRequest = { expanded = false }
        ) {
            listOf("English", "Chinese", "Spanish", "French", "Korean").forEach { lang ->
                DropdownMenuItem(
                    text = { Text(lang) },
                    onClick = {
                        onSelect(lang)
                        expanded = false
                    }
                )
            }
        }
    }
}
